


BEGIN
-- Verifica e remove a view se já existir
   EXECUTE IMMEDIATE 'DROP VIEW  INVISUAL.INS_CC_TEMPO_INTERNACAO_URG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


-- ======================================================================================
-- NOME DA DA VIEW: INS_CC_TEMPO_INTERNACAO_URG
-- VARIÁVEL COMMAND CENTER: Urgência - Tempo de Abertura de Ficha
-- PROPÓSITO: Monitora pacientes na urgencia aguardando internacao
-- CRIADO POR: Rubens
-- DATA DE CRIAÇÃO: **
-- ÚLTIMA ALTERAÇÃO: 28/04/2025 - Padronização de cabeçalho das views do IGESP
-- ======================================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVISUAL"."INS_CC_TEMPO_INTERNACAO_URG"  AS select
  CODIGOMULTIEMPRESA,
  CODIGOATENDIMENTO,
  DATAHORAINICIO,
  CODIGOPACIENTE,
  NOMEPACIENTE,
  DESCRICAOCONVENIO,
  CODIGOITEM,
  DESCRICAOITEM,
  DESCRICAOESPECIALIDADE,
  NOMESOLICITANTE,
  VALOR
 
From

(
 

  SELECT DISTINCT
  ATEND.CD_MULTI_EMPRESA CODIGOMULTIEMPRESA,
ATEND.CD_ATENDIMENTO as CODIGOATENDIMENTO,
TO_CHAR(DOC.DH_CRIACAO, 'YYYY-MM-DD HH24:MI:SS') as DATAHORAINICIO,
ATEND.CD_PACIENTE AS CODIGOPACIENTE,
dbamv.obter_iniciais_com_ponto(PAC.NM_PACIENTE) as NOMEPACIENTE,
CONV.NM_CONVENIO AS DESCRICAOCONVENIO,
atend.CD_ORI_ATE as CODIGOITEM,
ori.DS_ORI_ATE as DESCRICAOITEM,
esp.DS_ESPECIALID as DESCRICAOESPECIALIDADE,
prest.NM_PRESTADOR as NOMESOLICITANTE,
round((SYSDATE - DOC.DH_CRIACAO) * 1440) as VALOR
FROM dbamv.ATENDIME ATEND
left join dbamv.ori_ate ori on ori.CD_ORI_ATE=atend.CD_ORI_ATE
left join dbamv.paciente pac on atend.CD_PACIENTE=pac.CD_PACIENTE
LEFT JOIN dbamv.CONVENIO CONV ON ATEND.CD_CONVENIO=CONV.CD_CONVENIO
left join dbamv.especialid esp on esp.CD_ESPECIALID=atend.CD_ESPECIALID
left join dbamv.con_pla pla on atend.CD_CONVENIO=pla.CD_CONVENIO and atend.CD_CON_PLA=pla.CD_CON_PLA
LEFT JOIN dbamv.PW_DOCUMENTO_CLINICO DOC ON DOC.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO
left join dbamv.prestador prest on prest.CD_PRESTADOR=doc.CD_PRESTADOR
LEFT JOIN dbamv.PW_DOCUMENTO_OBJETO OBJ ON  OBJ.CD_OBJETO = DOC.CD_OBJETO
WHERE ATEND.TP_ATENDIMENTO = 'U'
AND DOC.NM_DOCUMENTO = 'SOLICITAÇÃO DE INTERNAÇÃO'
AND ATEND.DT_ALTA IS NULL
AND HR_ATENDIMENTO>=(sysdate - interval '10' hour)
and ATEND.CD_MULTI_EMPRESA =1
 


union all


 

  SELECT DISTINCT
  ATEND.CD_MULTI_EMPRESA CODIGOMULTIEMPRESA,
ATEND.CD_ATENDIMENTO as CODIGOATENDIMENTO,
TO_CHAR(DOC.DH_CRIACAO, 'YYYY-MM-DD HH24:MI:SS') as DATAHORAINICIO,
ATEND.CD_PACIENTE AS CODIGOPACIENTE,
dbamv.obter_iniciais_com_ponto(PAC.NM_PACIENTE) as NOMEPACIENTE,
CONV.NM_CONVENIO AS DESCRICAOCONVENIO,
atend.CD_ORI_ATE as CODIGOITEM,
ori.DS_ORI_ATE as DESCRICAOITEM,
esp.DS_ESPECIALID as DESCRICAOESPECIALIDADE,
prest.NM_PRESTADOR as NOMESOLICITANTE,
round((SYSDATE - DOC.DH_CRIACAO) * 1440) as VALOR
FROM dbamv.ATENDIME ATEND
left join dbamv.ori_ate ori on ori.CD_ORI_ATE=atend.CD_ORI_ATE
left join dbamv.paciente pac on atend.CD_PACIENTE=pac.CD_PACIENTE
LEFT JOIN dbamv.CONVENIO CONV ON ATEND.CD_CONVENIO=CONV.CD_CONVENIO
left join dbamv.especialid esp on esp.CD_ESPECIALID=atend.CD_ESPECIALID
left join dbamv.con_pla pla on atend.CD_CONVENIO=pla.CD_CONVENIO and atend.CD_CON_PLA=pla.CD_CON_PLA
LEFT JOIN dbamv.PW_DOCUMENTO_CLINICO DOC ON DOC.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO
left join dbamv.prestador prest on prest.CD_PRESTADOR=doc.CD_PRESTADOR
LEFT JOIN dbamv.PW_DOCUMENTO_OBJETO OBJ ON  OBJ.CD_OBJETO = DOC.CD_OBJETO
WHERE ATEND.TP_ATENDIMENTO = 'U'
AND DOC.NM_DOCUMENTO = 'SOLICITAÇÃO DE INTERNAÇÃO'
AND ATEND.DT_ALTA IS NULL
AND HR_ATENDIMENTO>=(sysdate - interval '10' hour)
and ATEND.CD_MULTI_EMPRESA =7


union all
  SELECT DISTINCT
  ATEND.CD_MULTI_EMPRESA CODIGOMULTIEMPRESA,
ATEND.CD_ATENDIMENTO as CODIGOATENDIMENTO,
TO_CHAR(DOC.DH_CRIACAO, 'YYYY-MM-DD HH24:MI:SS') as DATAHORAINICIO,
ATEND.CD_PACIENTE AS CODIGOPACIENTE,
dbamv.obter_iniciais_com_ponto(PAC.NM_PACIENTE) as NOMEPACIENTE,
CONV.NM_CONVENIO AS DESCRICAOCONVENIO,
atend.CD_ORI_ATE as CODIGOITEM,
ori.DS_ORI_ATE as DESCRICAOITEM,
esp.DS_ESPECIALID as DESCRICAOESPECIALIDADE,
prest.NM_PRESTADOR as NOMESOLICITANTE,
round((SYSDATE - DOC.DH_CRIACAO) * 1440) as VALOR
FROM dbamv.ATENDIME ATEND
left join dbamv.ori_ate ori on ori.CD_ORI_ATE=atend.CD_ORI_ATE
left join dbamv.paciente pac on atend.CD_PACIENTE=pac.CD_PACIENTE
LEFT JOIN dbamv.CONVENIO CONV ON ATEND.CD_CONVENIO=CONV.CD_CONVENIO
left join dbamv.especialid esp on esp.CD_ESPECIALID=atend.CD_ESPECIALID
left join dbamv.con_pla pla on atend.CD_CONVENIO=pla.CD_CONVENIO and atend.CD_CON_PLA=pla.CD_CON_PLA
LEFT JOIN dbamv.PW_DOCUMENTO_CLINICO DOC ON DOC.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO
left join dbamv.prestador prest on prest.CD_PRESTADOR=doc.CD_PRESTADOR
LEFT JOIN dbamv.PW_DOCUMENTO_OBJETO OBJ ON  OBJ.CD_OBJETO = DOC.CD_OBJETO
WHERE ATEND.TP_ATENDIMENTO = 'U'
AND DOC.NM_DOCUMENTO = 'SOLICITAÇÃO DE INTERNAÇÃO'
AND ATEND.DT_ALTA IS NULL
AND HR_ATENDIMENTO>=(sysdate - interval '10' hour)
and ATEND.CD_MULTI_EMPRESA = 9
and ATEND.CD_CONVENIO  NOT IN (40)

)  order by DATAHORAINICIO;
