


BEGIN
-- Verifica e remove a view se já existir
   EXECUTE IMMEDIATE 'DROP VIEW  INVISUAL.INS_CC_TEMPO_LAUDO_IMG_URG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


-- ======================================================================================
-- NOME DA DA VIEW: INS_CC_TEMPO_LAUDO_IMG_URG
-- VARIÁVEL COMMAND CENTER: Urgência - Tempo de Laudo de Exame de Imagem
-- PROPÓSITO: Monitora o tempo de laudo de exames de imagem na urgencia
-- CRIADO POR: Rubens
-- DATA DE CRIAÇÃO: **
-- ÚLTIMA ALTERAÇÃO: 28/04/2025 - Padronização de cabeçalho das views do IGESP
-- ======================================================================================


 CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVISUAL"."INS_CC_TEMPO_LAUDO_IMG_URG"  AS
 SELECT DISTINCT
  ATEND.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
ATEND.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
TO_CHAR(ITEM.DT_SOLICITACAO_GUIA, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
ATEND.CD_PACIENTE AS CODIGOPACIENTE,
dbamv.obter_iniciais_com_ponto(PAC.NM_PACIENTE) AS NOMEPACIENTE,
CONV.NM_CONVENIO AS DESCRICAOCONVENIO,
ESP.DS_ESPECIALID AS DESCRICAOESPECIALIDADE,
PREST.NM_PRESTADOR AS NOMESOLICITANTE,
PED.TP_MOTIVO AS TIPOSOLICITACAO,
PED.CD_PED_RX AS CodigoPedidoImg,
ITEM.CD_ITPED_RX AS CodigoItemPedidoImg,
ITEM.CD_EXA_RX AS CODIGOITEM,
DS_MODALIDADE_EXAME || '-' || EXA.DS_EXA_RX AS DESCRICAOITEM,
ROUND((SYSDATE - ITEM.DT_SOLICITACAO_GUIA) * 1440) AS VALOR
FROM DBAMV.ATENDIME ATEND
LEFT JOIN DBAMV.PACIENTE PAC ON ATEND.CD_PACIENTE=PAC.CD_PACIENTE
LEFT JOIN DBAMV.CONVENIO CONV ON ATEND.CD_CONVENIO=CONV.CD_CONVENIO
LEFT JOIN DBAMV.CON_PLA PLA ON ATEND.CD_CONVENIO=PLA.CD_CONVENIO AND ATEND.CD_CON_PLA=PLA.CD_CON_PLA
LEFT JOIN DBAMV.ESPECIALID ESP ON ESP.CD_ESPECIALID=ATEND.CD_ESPECIALID
LEFT JOIN DBAMV.PED_RX PED ON PED.CD_ATENDIMENTO=ATEND.CD_ATENDIMENTO
LEFT JOIN DBAMV.PRESTADOR PREST ON PREST.CD_PRESTADOR=PED.CD_PRESTADOR
left  JOIN DBAMV.ITPED_RX ITEM ON ITEM.CD_PED_RX=PED.CD_PED_RX
left  JOIN DBAMV.EXA_RX EXA ON EXA.CD_EXA_RX=ITEM.CD_EXA_RX
LEFT JOIN DBAMV.MODALIDADE_EXAME MODAL ON MODAL.CD_MODALIDADE_EXAME=EXA.CD_MODALIDADE_EXAME
WHERE ATEND.HR_ATENDIMENTO>=(sysdate - interval '10' hour)
AND ATEND.DT_ALTA IS NULL
and   ATEND.TP_ATENDIMENTO='U'
AND ITEM.CD_ITPED_RX IS NOT NULL
AND ITEM.CD_LAUDO IS NULL
AND ATEND.CD_MULTI_EMPRESA IN (1,7,9)
-- AND MODAL.DS_SIGLA_MODALIDADE<>'RX'
AND ITEM.DT_SOLICITACAO_GUIA IS NOT NULL
and    lower(ds_exa_rx)  not  like '%eletro%'
and     lower(ds_exa_rx) not like  '%holter%'
order by DATAHORAINICIO;
