

BEGIN
-- Verifica e remove a view se já existir
   EXECUTE IMMEDIATE 'DROP VIEW INVISUAL.INS_CC_PART_VALOR_FORA_PACOTE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


-- ======================================================================================
-- VIEW: INS_CC_PART_VALOR_FORA_PACOTE
-- VARIÁVEL COMMAND CENTER : Financeiro - Paciente Particular - Lançamento de Item Fora do Pacote
-- PROPÓSITO: Monitora paciente particular com itens lançados fora do pacote
-- CRIADO POR: Rodrigo / Gustavo
-- DATA DE CRIAÇÃO: 10/04/2025
-- ÚLTIMA ALTERAÇÃO: 15/04/2025 por Rodrigo - [JIRA CC-242] Criação da Variável - Cabeçalo adicionado ao arquivo
-- ======================================================================================



CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVISUAL"."INS_CC_PART_VALOR_FORA_PACOTE" AS

SELECT
    A.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
    C2.NM_CONVENIO AS DESCRICAOCONVENIO,
    A.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
    'PS' AS TIPOATENDIMENTO,
    RA.CD_REG_AMB AS CODIGOCONTA,
    A.CD_PACIENTE AS CODIGOPACIENTE,
    P.NM_PACIENTE AS NOMEPACIENTE,
    TO_CHAR(IRA.HR_LANCAMENTO, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
    IRA.CD_PRO_FAT AS CODIGOITEM,
    PF.DS_PRO_FAT AS DESCRICAOITEM,
    IRA.VL_TOTAL_CONTA AS VALOR

FROM DBAMV.REG_AMB RA
LEFT JOIN DBAMV.ITREG_AMB IRA ON RA.CD_REG_AMB = IRA.CD_REG_AMB
LEFT JOIN DBAMV.CONVENIO C1 ON RA.CD_CONVENIO = C1.CD_CONVENIO
LEFT JOIN DBAMV.ATENDIME A ON IRA.CD_ATENDIMENTO = A.CD_ATENDIMENTO
LEFT JOIN DBAMV.CONVENIO C2 ON A.CD_CONVENIO = C2.CD_CONVENIO
LEFT JOIN DBAMV.PACIENTE P ON A.CD_PACIENTE = P.CD_PACIENTE
LEFT JOIN DBAMV.PRO_FAT PF ON IRA.CD_PRO_FAT = PF.CD_PRO_FAT

WHERE
    A.DT_ATENDIMENTO >= TO_DATE('01/01/2025', 'DD/MM/YYYY') AND
    A.TP_ATENDIMENTO = 'U' AND
    C1.TP_CONVENIO = 'P' AND
    C2.TP_CONVENIO = 'P' AND
    IRA.SN_PERTENCE_PACOTE = 'N' AND
    NVL(IRA.TP_PAGAMENTO, 'P') <> 'C' AND
    NVL(RA.SN_DIAGNO, 'N') = 'N' AND
    IRA.VL_TOTAL_CONTA > 0 AND
    ROUND(
        (IRA.VL_TOTAL_CONTA /
            (SELECT SUM(IRA2.VL_TOTAL_CONTA)
             FROM DBAMV.ITREG_AMB IRA2
             WHERE IRA2.CD_REG_AMB = RA.CD_REG_AMB
             AND IRA2.SN_PERTENCE_PACOTE = 'N')) *
        (SELECT SUM(NVL(RCR.VL_RECEBIDO, 0)) - SUM(NVL(RCR.VL_ACRESCIMO, 0)) + SUM(NVL(RCR.VL_DESCONTO, 0))
         FROM DBAMV.RECCON_REC RCR
         JOIN DBAMV.ITCON_REC ICR ON RCR.CD_ITCON_REC = ICR.CD_ITCON_REC
         JOIN DBAMV.CON_REC CR ON ICR.CD_CON_REC = CR.CD_CON_REC
         WHERE CR.CD_ATENDIMENTO = A.CD_ATENDIMENTO
         AND CR.CD_REG_AMB = RA.CD_REG_AMB),
        2
    ) IS NULL

UNION ALL

SELECT
    A.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
    C2.NM_CONVENIO AS DESCRICAOCONVENIO,
    A.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
    'INTERNACAO' AS TIPOATENDIMENTO,
    RF.CD_REG_FAT AS CODIGOCONTA,
    A.CD_PACIENTE AS CODIGOPACIENTE,
    P.NM_PACIENTE AS NOMEPACIENTE,
    TO_CHAR(IFA.HR_LANCAMENTO, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
    IFA.CD_PRO_FAT AS CODIGOITEM,
    PF.DS_PRO_FAT AS DESCRICAOITEM,
    IFA.VL_TOTAL_CONTA AS VALOR

FROM DBAMV.REG_FAT RF
LEFT JOIN DBAMV.ITREG_FAT IFA ON RF.CD_REG_FAT = IFA.CD_REG_FAT
LEFT JOIN DBAMV.CONVENIO C1 ON RF.CD_CONVENIO = C1.CD_CONVENIO
LEFT JOIN DBAMV.ATENDIME A ON RF.CD_ATENDIMENTO = A.CD_ATENDIMENTO
LEFT JOIN DBAMV.CONVENIO C2 ON A.CD_CONVENIO = C2.CD_CONVENIO
LEFT JOIN DBAMV.PACIENTE P ON A.CD_PACIENTE = P.CD_PACIENTE
LEFT JOIN DBAMV.PRO_FAT PF ON IFA.CD_PRO_FAT = PF.CD_PRO_FAT

WHERE
    A.DT_ATENDIMENTO >= TO_DATE('01/01/2025', 'DD/MM/YYYY') AND
    A.TP_ATENDIMENTO = 'I' AND
    C1.TP_CONVENIO = 'P' AND
    C2.TP_CONVENIO = 'P' AND
    IFA.SN_PERTENCE_PACOTE = 'N' AND
    NVL(IFA.TP_PAGAMENTO, 'P') <> 'C' AND
    NVL(RF.SN_DIAGNO, 'N') = 'N' AND
    IFA.VL_TOTAL_CONTA > 0 AND
    (
        (IFA.VL_TOTAL_CONTA /
            (SELECT SUM(IFA2.VL_TOTAL_CONTA)
             FROM DBAMV.ITREG_FAT IFA2
             WHERE IFA2.CD_REG_FAT = RF.CD_REG_FAT
             AND IFA2.SN_PERTENCE_PACOTE = 'N')) *
        (SELECT SUM(NVL(RCR.VL_RECEBIDO, 0)) - SUM(NVL(RCR.VL_ACRESCIMO, 0)) + SUM(NVL(RCR.VL_DESCONTO, 0))
         FROM DBAMV.RECCON_REC RCR
         JOIN DBAMV.ITCON_REC ICR ON RCR.CD_ITCON_REC = ICR.CD_ITCON_REC
         JOIN DBAMV.CON_REC CR ON ICR.CD_CON_REC = CR.CD_CON_REC
         WHERE CR.CD_ATENDIMENTO = A.CD_ATENDIMENTO
         AND CR.CD_REG_FAT = RF.CD_REG_FAT)
    ) IS NULL;
