-- Verifica e remove a view se já existir
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW INVISUAL.INS_CC_MON_ALTA_MED_HOSP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- ======================================================================================
-- VIEW: INS_CC_MON_ALTA_MED_HOSP
-- VARIÁVEL COMMAND CENTER : Leitos - Tempo de Alta Hospitalar 
-- PROPÓSITO: Monitora alta hospitalar de pacientes com alta médica
-- CRIADO POR: Rodrigo
-- DATA DE CRIAÇÃO:  ** 2024
-- ÚLTIMA ALTERAÇÃO: 15/04/2025 por Rodrigo - [JIRA-CC-241] Orientação sobre a criação de 2 novas regras , aproveitando essa variável
-- ======================================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVISUAL"."INS_CC_MON_ALTA_MED_HOSP" AS

WITH Tbl_Mon_Alta_Hosp AS (
  SELECT DISTINCT
    atend.HR_ALTA_MEDICA,
    atend.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
    atend.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
    TO_CHAR(atend.HR_ALTA_MEDICA, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
    atend.CD_PACIENTE AS CODIGOPACIENTE,
    pac.NM_PACIENTE AS NOMEPACIENTE,
    conv.NM_CONVENIO AS DESCRICAOCONVENIO,
    atend.CD_ORI_ATE AS CODIGOITEM,
    ori.DS_ORI_ATE AS DESCRICAOITEM,
    esp.DS_ESPECIALID AS DESCRICAOESPECIALIDADE,
    prest.NM_PRESTADOR AS NOMESOLICITANTE,
    ROUND((SYSDATE - atend.HR_ALTA_MEDICA) * 1440) AS VALOR

  FROM DBAMV.ATENDIME atend
  LEFT JOIN DBAMV.ORI_ATE ori ON ori.CD_ORI_ATE = atend.CD_ORI_ATE
  LEFT JOIN DBAMV.SETOR setor ON setor.CD_SETOR = ori.CD_SETOR
  LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO_HISTORICO hist ON hist.CD_ATENDIMENTO = atend.CD_ATENDIMENTO
  LEFT JOIN DBAMV.PACIENTE pac ON atend.CD_PACIENTE = pac.CD_PACIENTE
  LEFT JOIN DBAMV.PRESTADOR prest ON prest.CD_PRESTADOR = atend.CD_PRESTADOR
  LEFT JOIN DBAMV.CONVENIO conv ON atend.CD_CONVENIO = conv.CD_CONVENIO
  LEFT JOIN DBAMV.CON_PLA pla ON atend.CD_CONVENIO = pla.CD_CONVENIO AND atend.CD_CON_PLA = pla.CD_CON_PLA
  LEFT JOIN DBAMV.ESPECIALID esp ON esp.CD_ESPECIALID = atend.CD_ESPECIALID

  WHERE (
          (atend.HR_ALTA_MEDICA BETWEEN SYSDATE - INTERVAL '24' HOUR AND SYSDATE + INTERVAL '24' HOUR)
       OR (atend.DT_ALTA_MEDICA BETWEEN SYSDATE - INTERVAL '24' HOUR AND SYSDATE + INTERVAL '24' HOUR)
        )
    AND atend.HR_ALTA_MEDICA IS NOT NULL
    AND atend.DT_ALTA IS NULL
)

SELECT
  Mah.CODIGOMULTIEMPRESA,
  Mah.CODIGOATENDIMENTO,
  Mah.DATAHORAINICIO,
  Mah.CODIGOPACIENTE,
  Mah.NOMEPACIENTE,
  Mah.DESCRICAOCONVENIO,
  Mah.CODIGOITEM,
  Mah.DESCRICAOITEM,
  Mah.DESCRICAOESPECIALIDADE,
  Mah.NOMESOLICITANTE,
  Mah.VALOR
FROM Tbl_Mon_Alta_Hosp Mah
WHERE Mah.HR_ALTA_MEDICA >= (SYSDATE - INTERVAL '24' HOUR)
ORDER BY Mah.HR_ALTA_MEDICA;
