

BEGIN
-- Verifica e remove a view se já existir
   EXECUTE IMMEDIATE 'DROP VIEW INVISUAL.INS_CC_TEMPO_ATENDIMENTO_URG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


-- ======================================================================================
-- NOME DA DA VIEW: INS_CC_TEMPO_ATENDIMENTO_URG 
-- VARIÁVEL COMMAND CENTER: Urgência - Tempo de Atendimento Médico Inicial
-- PROPÓSITO: Monitora pacientes aguardando atendimento médico na urgência
-- CRIADO POR: Rubens
-- DATA DE CRIAÇÃO: **
-- ÚLTIMA ALTERAÇÃO: 15/04/2025 por Rodrigo  - Adicionei cabeçalho de informações E Refatorei a query /  [JIRA-CC-239] Nenhuma ação , pois a variavel contemplará a nova regra
-- ======================================================================================



-- Criação da view
CREATE OR REPLACE FORCE EDITIONABLE VIEW INVISUAL.INS_CC_TEMPO_ATENDIMENTO_URG AS
SELECT DISTINCT 
    ATEND.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
    ATEND.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
    TO_CHAR(ATEND.HR_ATENDIMENTO, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
    ATEND.CD_PACIENTE AS CODIGOPACIENTE,
    PAC.NM_PACIENTE AS NOMEPACIENTE,
    CONV.NM_CONVENIO AS DESCRICAOCONVENIO,
    ESP.DS_ESPECIALID AS DESCRICAOESPECIALIDADE,
    PREST.NM_PRESTADOR AS DESCRICAOITEM,
    COR.NM_COR AS NOMECOR,
    ROUND((SYSDATE - ATEND.HR_ATENDIMENTO) * 1440) AS VALOR
FROM DBAMV.ATENDIME ATEND
LEFT JOIN DBAMV.SACR_TEMPO_PROCESSO_HISTORICO HIST 
    ON HIST.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO
LEFT JOIN DBAMV.PACIENTE PAC 
    ON ATEND.CD_PACIENTE = PAC.CD_PACIENTE
LEFT JOIN DBAMV.PRESTADOR PREST 
    ON PREST.CD_PRESTADOR = ATEND.CD_PRESTADOR
LEFT JOIN DBAMV.CONVENIO CONV 
    ON ATEND.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN DBAMV.CON_PLA PLA 
    ON ATEND.CD_CONVENIO = PLA.CD_CONVENIO AND ATEND.CD_CON_PLA = PLA.CD_CON_PLA
LEFT JOIN DBAMV.ESPECIALID ESP 
    ON ESP.CD_ESPECIALID = ATEND.CD_ESPECIALID
LEFT JOIN DBAMV.TRIAGEM_ATENDIMENTO TRIAG 
    ON ATEND.CD_ATENDIMENTO = TRIAG.CD_ATENDIMENTO
LEFT JOIN DBAMV.SACR_CLASSIFICACAO_RISCO CLASSIF  
    ON CLASSIF.CD_TRIAGEM_ATENDIMENTO = TRIAG.CD_TRIAGEM_ATENDIMENTO
LEFT JOIN DBAMV.SACR_COR_REFERENCIA COR 
    ON COR.CD_COR_REFERENCIA = CLASSIF.CD_COR_REFERENCIA
WHERE ATEND.HR_ATENDIMENTO >= (SYSDATE - INTERVAL '10' HOUR)
  AND ATEND.DT_ALTA IS NULL
  AND ATEND.TP_ATENDIMENTO = 'U'
  AND ATEND.CD_ORI_ATE NOT IN (15, 96)
  AND HIST.CD_TIPO_TEMPO_PROCESSO NOT IN (30, 31, 32)
  AND (SELECT COUNT(*) FROM PRE_MED PREM WHERE PREM.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO) = 0
  AND (SELECT COUNT(*) FROM PED_LAB LAB WHERE LAB.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO) = 0
  AND (SELECT COUNT(*) FROM PED_RX RX WHERE RX.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO) = 0
  AND (SELECT COUNT(*) FROM REGISTRO_DOCUMENTO DOC WHERE DOC.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO) = 0
  AND (
        SELECT COUNT(*) 
        FROM PW_DOCUMENTO_CLINICO PWDOC 
        WHERE PWDOC.CD_ATENDIMENTO = ATEND.CD_ATENDIMENTO 
          AND PWDOC.CD_TIPO_DOCUMENTO NOT IN (17, 19, 24)
      ) = 0
ORDER BY DATAHORAINICIO;
