{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 -- ======================================================================================\
-- VIEW: INS_CC_TEMPO_LAUDO_IMG_URG\
-- PROP\'d3SITO: Monitora o tempo de laudo de exames de imagem na urg\'eancia\
-- CRIADO POR:  Rubens\
-- DATA DE CRIA\'c7\'c3O: 15/04/2025\
-- \'daLTIMA ALTERA\'c7\'c3O: 15/04/2025  por Fulano - [JIRA-123] Ajuste em filtros de data\
-- ======================================================================================\
\
\
 CREATE OR REPLACE FORCE EDITIONABLE VIEW "INVISUAL"."INS_CC_TEMPO_LAUDO_IMG_URG"  AS\
\
\
 SELECT DISTINCT \
  ATEND.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,\
ATEND.CD_ATENDIMENTO AS CODIGOATENDIMENTO,\
TO_CHAR(ITEM.DT_SOLICITACAO_GUIA, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,\
ATEND.CD_PACIENTE AS CODIGOPACIENTE,\
PAC.NM_PACIENTE AS NOMEPACIENTE,\
CONV.NM_CONVENIO AS DESCRICAOCONVENIO,\
ESP.DS_ESPECIALID AS DESCRICAOESPECIALIDADE,\
PREST.NM_PRESTADOR AS NOMESOLICITANTE,\
PED.TP_MOTIVO AS TIPOSOLICITACAO,\
PED.CD_PED_RX AS CodigoPedidoImg,\
ITEM.CD_ITPED_RX AS CodigoItemPedidoImg,\
ITEM.CD_EXA_RX AS CODIGOITEM,\
EXA.DS_EXA_RX AS DESCRICAOITEM,\
ROUND((SYSDATE - ITEM.DT_SOLICITACAO_GUIA) * 1440) AS VALOR\
FROM DBAMV.ATENDIME ATEND \
LEFT JOIN DBAMV.PACIENTE PAC ON ATEND.CD_PACIENTE=PAC.CD_PACIENTE\
LEFT JOIN DBAMV.CONVENIO CONV ON ATEND.CD_CONVENIO=CONV.CD_CONVENIO\
LEFT JOIN DBAMV.CON_PLA PLA ON ATEND.CD_CONVENIO=PLA.CD_CONVENIO AND ATEND.CD_CON_PLA=PLA.CD_CON_PLA\
LEFT JOIN DBAMV.ESPECIALID ESP ON ESP.CD_ESPECIALID=ATEND.CD_ESPECIALID\
LEFT JOIN DBAMV.PED_RX PED ON PED.CD_ATENDIMENTO=ATEND.CD_ATENDIMENTO\
LEFT JOIN DBAMV.PRESTADOR PREST ON PREST.CD_PRESTADOR=PED.CD_PRESTADOR\
LEFT JOIN DBAMV.ITPED_RX ITEM ON ITEM.CD_PED_RX=PED.CD_PED_RX\
LEFT JOIN DBAMV.EXA_RX EXA ON EXA.CD_EXA_RX=ITEM.CD_EXA_RX\
LEFT JOIN DBAMV.MODALIDADE_EXAME MODAL ON MODAL.CD_MODALIDADE_EXAME=EXA.CD_MODALIDADE_EXAME\
WHERE ATEND.HR_ATENDIMENTO>=(sysdate - interval '10' hour)\
AND ATEND.DT_ALTA IS NULL\
AND ATEND.TP_ATENDIMENTO='U'\
AND ITEM.CD_ITPED_RX IS NOT NULL\
AND ITEM.CD_LAUDO IS NULL\
AND MODAL.DS_SIGLA_MODALIDADE<>'CR'\
AND ITEM.DT_SOLICITACAO_GUIA IS NOT NULL\
order by DATAHORAINICIO;\
\
}