
BEGIN
-- Verifica e remove a view se já existir
   EXECUTE IMMEDIATE 'DROP VIEW INVISUAL.INS_CC_PERC_ADIANT_CONTA';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


-- ======================================================================================
-- NOME DA VIEW: INS_CC_PERC_ADIANT_CONTA
-- VARIÁVEL COMMAND CENTER : Financeiro - Paciente Particular - Percentagem do Adiantamento da Conta
-- PROPÓSITO: Monitora o valor da conta e compara com o adiantamento. 
--            Dispara alerta quando o valor da conta atinge 90% do adiantamento.
-- CRIADO POR: Rodrigo / Gustavo
-- DATA DE CRIAÇÃO: 10/04/2025
-- ÚLTIMA ALTERAÇÃO: 15/04/2025 por Rodrigo - [JIRA-CC- 243] Alterei o filtro de 70% para 80% 
-- ======================================================================================



-- Criação da view
CREATE OR REPLACE FORCE EDITIONABLE VIEW INVISUAL.INS_CC_PERC_ADIANT_CONTA AS
SELECT
    ATEND.CD_MULTI_EMPRESA AS CODIGOMULTIEMPRESA,
    ATEND.CD_ATENDIMENTO AS CODIGOATENDIMENTO,
    TO_CHAR(ATEND.DT_ATENDIMENTO, 'YYYY-MM-DD HH24:MI:SS') AS DATAHORAINICIO,
    ATEND.CD_PACIENTE AS CODIGOPACIENTE,
    PAC.NM_PACIENTE AS NOMEPACIENTE,
    LISTAGG(RF.CD_REG_FAT, ', ') WITHIN GROUP (ORDER BY RF.CD_REG_FAT) AS CODIGOCONTA,
    ROUND(
        NVL(SUM(RF.VL_TOTAL_CONTA), 0) / 
        NULLIF((NVL(CAUCAO.VL_CAUCAO, 0) + NVL(CONT.VL_CONTRATO_ADIANT, 0)), 0),
        2
    ) * 100 AS VALOR
FROM DBAMV.ATENDIME ATEND
LEFT JOIN DBAMV.CONVENIO CONV 
    ON ATEND.CD_CONVENIO = CONV.CD_CONVENIO
LEFT JOIN DBAMV.PACIENTE PAC 
    ON ATEND.CD_PACIENTE = PAC.CD_PACIENTE
LEFT JOIN DBAMV.REG_FAT RF 
    ON ATEND.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
LEFT JOIN (
    SELECT CD_ATENDIMENTO, SUM(VL_CAUCAO) AS VL_CAUCAO
    FROM DBAMV.CAUCAO
    GROUP BY CD_ATENDIMENTO
) CAUCAO 
    ON ATEND.CD_ATENDIMENTO = CAUCAO.CD_ATENDIMENTO
LEFT JOIN (
    SELECT CD_ATENDIMENTO, SUM(VL_CONTRATO_ADIANT) AS VL_CONTRATO_ADIANT
    FROM DBAMV.CONTRATO_ADIANTAMENTO
    WHERE SN_RECEBIDO = 'S'
    GROUP BY CD_ATENDIMENTO
) CONT 
    ON ATEND.CD_ATENDIMENTO = CONT.CD_ATENDIMENTO
WHERE ATEND.TP_ATENDIMENTO = 'I'
  AND CONV.TP_CONVENIO = 'P'
  AND ATEND.DT_ATENDIMENTO >= TO_DATE('01/01/' || TO_CHAR(SYSDATE, 'YYYY'), 'DD/MM/YYYY')
  AND ATEND.DT_ALTA IS NULL
GROUP BY
    ATEND.CD_MULTI_EMPRESA,
    ATEND.CD_ATENDIMENTO,
    TO_CHAR(ATEND.DT_ATENDIMENTO, 'YYYY-MM-DD HH24:MI:SS'),
    ATEND.CD_PACIENTE,
    PAC.NM_PACIENTE,
    CAUCAO.VL_CAUCAO,
    CONT.VL_CONTRATO_ADIANT
HAVING
    NVL(CAUCAO.VL_CAUCAO, 0) + NVL(CONT.VL_CONTRATO_ADIANT, 0) > 0
    AND NVL(SUM(RF.VL_TOTAL_CONTA), 0) >= 
        (NVL(CAUCAO.VL_CAUCAO, 0) + NVL(CONT.VL_CONTRATO_ADIANT, 0)) * 0.9 -- 90% ou mais do valor adiantado
ORDER BY
    ATEND.CD_ATENDIMENTO;
